---
title: "Premier League Spending"
author: "Trent Bellinger"
date: "10/27/2022"
output: html_document
---

```{r Loading in Data}
library(ggplot2)
library(ggimage)
library(grid)
library(png)
library(ggtext)

prem_data1 <- read.csv("PremSpendingData.csv")
prem_data2 <- prem_data1[1:25, ]

prem_images <- c("ManCity.png", "Chelsea.png", "ManU.png", "Liverpool.png", "Arsenal.png", 
            "Tottenham.png", "Everton.png", "Villa.png", "WestHam.png", "Newcastle.png", "Leicester.png", "Southampton.png", 
            "Wolves.png", "Palace.png", "Watford.png", "Brighton.png", "Fulham.png", "Bournemouth.png", "Stoke.png", 
            "WestBrom.png", "Norwich.png", "Sunderland.png", "Leeds.png", "Burnley.png", "Middlesbrough.png")
prem_data <- data.frame(prem_data2, prem_images)
head(prem_data)
```

``` {r Graph 1 - League Position}
league_pos <- data.frame("Expenditure" = c(1.83e+09, 1.74e+09, 1.64e+09, 1.20e+09, 1.18e+09, 9.75e+08, 8.50e+08, 7.11e+08, 7.02e+08,
                                           6.91e+08, 6.81e+08, 6.35e+08, 5.04e+08, 4.10e+08, 4.03e+08, 3.91e+08, 3.76e+08, 3.29e+08,
                                           3.12e+08, 3.04e+08, 2.86e+08, 2.61e+08, 2.60e+08, 2.56e+08, 2.13e+08), 
                         "Average.Finish" = c(1.8, 3.9, 3.7, 4.5, 4.9, 4.3, 9.6, 17, 11.2, 13.3, 10.3, 12.9, 15.7, 14.2, 17.3, 
                                               17.2, 17.8, 17.3, 15.7, 15.4, 18.2, 18.3, 18.6, 16.2, 19.9), 
                         "Prem.Images" = prem_images)
linear_model <- lm(Average.Finish ~ Expenditure, data = league_pos)
summary(linear_model)
# Average.Finish = -1.098e-08 * Expenditure + 20.29
# r-squared = 0.8656

ggplot(league_pos, aes(x = Expenditure, y = Average.Finish)) +
  # geom_point(size = 2, color = "darkred") +
  geom_smooth(formula = y ~ x, method=lm, linetype="solid", color="darkred") +
  geom_image(aes(image = Prem.Images), size = 0.03) +
  # geom_text(aes(label = Club), vjust = -0.8, size = 2.2, color = "black") +
  scale_color_gradient(low = "yellow", high = "darkred") +
  # xlim(min = 2e8, max = 1.9e9) +
  # scale_x_continuous(limits = c(2e8, 1.85e9), labels = "comma", n.breaks = 10) +
  ylim(min = 20, max = -3) + 
  ggtitle("Top 25 Premier League Clubs Expenditure vs. Average Lxeague Position") +
  labs(y = "Average League Finish \n (non-premier league finishes counted as 20th)", x = "Money Spent in the Last Ten Years ($)") +
  theme(panel.background = element_rect(fill = "lightblue", color = "white")) +
  theme(title = element_text(face = "bold.italic", color = "black"), axis.title = element_text(face = "bold.italic", color = "black")) # +
  # geom_text(x = 600000000, y = 0, label = "Average.Finish = -1.098e-08 * Expenditure + 20.29 \n r^2 = 0.8656", family = "Times")
```

```{r Graph 2 - UCL}
prem_data_new <- read.csv("PremSpending2.csv")
prem_data_only_ucl1 <- prem_data_new[c(1:19, 21:28, 31:36, 41:46, 51:54, 101), ]
prem_images_only_ucl <- prem_images[c(rep(1, 10), rep(2, 9), rep(3, 8), rep(4, 6), rep(5, 6), rep(6, 4), 11)]
prem_data_only_ucl <- data.frame(prem_data_only_ucl1, prem_images_only_ucl)
head(prem_data_only_ucl)

ggplot(data = prem_data_only_ucl, aes(x = reorder(Club, Expenditure), y = UCL.Appearances, fill = reorder(UCL.Performance, UCL.Performance.Order))) +
  geom_bar(stat = "identity", color = "white") + 
  scale_fill_manual(values = c("gold", "grey", "lightskyblue4", "royalblue3", "steelblue2", "lightskyblue1")) +
  theme(axis.text.x = element_text(angle = 15)) +
  labs(x = "Premier League Club", y = "Champions League Appearances \n (in the last 10 years)", fill = "UCL Finish") +
  ggtitle("Premier League Clubs Champions League Finishes") +
  theme(panel.background = element_rect(fill = "gray95", color = "white")) +
  theme(title = element_text(face = "bold.italic", color = "black"), axis.title = element_text(face = "bold.italic", color = "black"))
  # geom_text(aes(label = Expenditure), vjust = -0.5, position = position_dodge(.9), size = 1) +
  # geom_image(aes(label = prem_images_only_ucl), position = "identity")
```

```{r Graph 3 - UCL Money Earned}
prem_data_ucl <- data.frame("Expenditure" = c(1.83e+09, 1.74e+09, 1.64e+09, 1.20e+09, 1.18e+09, 9.75e+08, 6.81e+08), 
                            "Money.Made.UCL" = c(3.61e+08, 3.45e+08, 1.95e+08, 2.89e+08, 1.53e+08, 1.31e+08, 3.60e+07), 
                            "prem_images_ucl" = prem_images[c(1:6, 11)])
head(prem_data_ucl)

ggplot(data = prem_data_ucl, aes(x = Expenditure, y = Money.Made.UCL)) +
  geom_smooth(formula = y ~ x, method=lm, linetype="solid", color="darkred") +
  geom_image(aes(image = prem_images_ucl), size = 0.04) +
  xlim(min = 6.7e+08, max = 1.85e+09) +
  ylim(min = -1e+08, max = 4.5e+08) +
  labs(x = "Expenditure", y = "Money Made From Champions League") +
  ggtitle("Premier League Clubs Money Made From Champions League") + 
  theme(panel.background = element_rect(fill = "lightblue", color = "white")) +
  theme(title = element_text(face = "bold.italic", color = "black"), axis.title = element_text(face = "bold.italic", color = "black"))
```




